// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.2
// source: file_thumb.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileThumb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: bson:"thumb_id" json:"thumb_id" xorm:"pk"
	ThumbId int64 `protobuf:"varint,1,opt,name=thumb_id,json=thumbId,proto3" json:"thumb_id" bson:"thumb_id" xorm:"pk"`
	// @gotags: bson:"file_id" json:"file_id" xorm:"unique(file_id_thumb_spec)"
	FileId int64 `protobuf:"varint,2,opt,name=file_id,json=fileId,proto3" json:"file_id" bson:"file_id" xorm:"unique(file_id_thumb_spec)"`
	// @gotags: bson:"thumb_name" json:"thumb_name"
	ThumbName string `protobuf:"bytes,3,opt,name=thumb_name,json=thumbName,proto3" json:"thumb_name" bson:"thumb_name"`
	// @gotags: bson:"thumb_type" json:"thumb_type"
	ThumbType string `protobuf:"bytes,4,opt,name=thumb_type,json=thumbType,proto3" json:"thumb_type" bson:"thumb_type"`
	// @gotags: bson:"thumb_path" json:"thumb_path"
	ThumbPath string `protobuf:"bytes,5,opt,name=thumb_path,json=thumbPath,proto3" json:"thumb_path" bson:"thumb_path"`
	// @gotags: bson:"thumb_size" json:"thumb_size"
	ThumbSize int64 `protobuf:"varint,6,opt,name=thumb_size,json=thumbSize,proto3" json:"thumb_size" bson:"thumb_size"`
	// @gotags: bson:"thumb_spec" json:"thumb_spec" xorm:"unique(file_id_thumb_spec)"
	ThumbSpec string `protobuf:"bytes,7,opt,name=thumb_spec,json=thumbSpec,proto3" json:"thumb_spec" bson:"thumb_spec" xorm:"unique(file_id_thumb_spec)"`
	// @gotags: bson:"created_at" json:"created_at" xorm:"created"
	CreatedAt int64 `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at" bson:"created_at" xorm:"created"`
	// @gotags: bson:"attributes" json:"attributes"
	Attributes map[string]string `protobuf:"bytes,9,rep,name=attributes,proto3" json:"attributes" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3" bson:"attributes"`
}

func (x *FileThumb) Reset() {
	*x = FileThumb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_thumb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileThumb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileThumb) ProtoMessage() {}

func (x *FileThumb) ProtoReflect() protoreflect.Message {
	mi := &file_file_thumb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileThumb.ProtoReflect.Descriptor instead.
func (*FileThumb) Descriptor() ([]byte, []int) {
	return file_file_thumb_proto_rawDescGZIP(), []int{0}
}

func (x *FileThumb) GetThumbId() int64 {
	if x != nil {
		return x.ThumbId
	}
	return 0
}

func (x *FileThumb) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *FileThumb) GetThumbName() string {
	if x != nil {
		return x.ThumbName
	}
	return ""
}

func (x *FileThumb) GetThumbType() string {
	if x != nil {
		return x.ThumbType
	}
	return ""
}

func (x *FileThumb) GetThumbPath() string {
	if x != nil {
		return x.ThumbPath
	}
	return ""
}

func (x *FileThumb) GetThumbSize() int64 {
	if x != nil {
		return x.ThumbSize
	}
	return 0
}

func (x *FileThumb) GetThumbSpec() string {
	if x != nil {
		return x.ThumbSpec
	}
	return ""
}

func (x *FileThumb) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *FileThumb) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_file_thumb_proto protoreflect.FileDescriptor

var file_file_thumb_proto_rawDesc = []byte{
	0x0a, 0x10, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0xfa, 0x02, 0x0a, 0x09, 0x46, 0x69,
	0x6c, 0x65, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x68, 0x75, 0x6d, 0x62,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x68, 0x75, 0x6d, 0x62,
	0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x74,
	0x68, 0x75, 0x6d, 0x62, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x68,
	0x75, 0x6d, 0x62, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x74, 0x68, 0x75, 0x6d, 0x62, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x68, 0x75,
	0x6d, 0x62, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74,
	0x68, 0x75, 0x6d, 0x62, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x68, 0x75, 0x6d,
	0x62, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x68,
	0x75, 0x6d, 0x62, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x68, 0x75, 0x6d, 0x62,
	0x5f, 0x73, 0x70, 0x65, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x68, 0x75,
	0x6d, 0x62, 0x53, 0x70, 0x65, 0x63, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x40, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x2e, 0x41, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x61, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x1a, 0x3d, 0x0a, 0x0f, 0x41, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2e, 0x2f, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_file_thumb_proto_rawDescOnce sync.Once
	file_file_thumb_proto_rawDescData = file_file_thumb_proto_rawDesc
)

func file_file_thumb_proto_rawDescGZIP() []byte {
	file_file_thumb_proto_rawDescOnce.Do(func() {
		file_file_thumb_proto_rawDescData = protoimpl.X.CompressGZIP(file_file_thumb_proto_rawDescData)
	})
	return file_file_thumb_proto_rawDescData
}

var file_file_thumb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_file_thumb_proto_goTypes = []interface{}{
	(*FileThumb)(nil), // 0: model.FileThumb
	nil,               // 1: model.FileThumb.AttributesEntry
}
var file_file_thumb_proto_depIdxs = []int32{
	1, // 0: model.FileThumb.attributes:type_name -> model.FileThumb.AttributesEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_file_thumb_proto_init() }
func file_file_thumb_proto_init() {
	if File_file_thumb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_file_thumb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileThumb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_file_thumb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_file_thumb_proto_goTypes,
		DependencyIndexes: file_file_thumb_proto_depIdxs,
		MessageInfos:      file_file_thumb_proto_msgTypes,
	}.Build()
	File_file_thumb_proto = out.File
	file_file_thumb_proto_rawDesc = nil
	file_file_thumb_proto_goTypes = nil
	file_file_thumb_proto_depIdxs = nil
}
