// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v4.25.3
// source: internal/model/gateway.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gateway struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip             string  `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip" bson:"ip"`
	ClientTotal    int64   `protobuf:"varint,2,opt,name=client_total,json=clientTotal,proto3" json:"client_total" bson:"client_total"`
	SendTotal      int64   `protobuf:"varint,3,opt,name=send_total,json=sendTotal,proto3" json:"send_total" bson:"send_total"`
	ReceivedTotal  int64   `protobuf:"varint,4,opt,name=received_total,json=receivedTotal,proto3" json:"received_total" bson:"received_total"`
	InvalidTotal   int64   `protobuf:"varint,5,opt,name=invalid_total,json=invalidTotal,proto3" json:"invalid_total" bson:"invalid_total"`
	GoroutineTotal int64   `protobuf:"varint,6,opt,name=goroutine_total,json=goroutineTotal,proto3" json:"goroutine_total" bson:"goroutine_total"`
	MemUsed        float32 `protobuf:"fixed32,7,opt,name=mem_used,json=memUsed,proto3" json:"mem_used" bson:"mem_used"`
	CpuUsed        float32 `protobuf:"fixed32,8,opt,name=cpu_used,json=cpuUsed,proto3" json:"cpu_used" bson:"cpu_used"`
}

func (x *Gateway) Reset() {
	*x = Gateway{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_model_gateway_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gateway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gateway) ProtoMessage() {}

func (x *Gateway) ProtoReflect() protoreflect.Message {
	mi := &file_internal_model_gateway_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use gateway.ProtoReflect.Descriptor instead.
func (*Gateway) Descriptor() ([]byte, []int) {
	return file_internal_model_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *Gateway) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Gateway) GetClientTotal() int64 {
	if x != nil {
		return x.ClientTotal
	}
	return 0
}

func (x *Gateway) GetSendTotal() int64 {
	if x != nil {
		return x.SendTotal
	}
	return 0
}

func (x *Gateway) GetReceivedTotal() int64 {
	if x != nil {
		return x.ReceivedTotal
	}
	return 0
}

func (x *Gateway) GetInvalidTotal() int64 {
	if x != nil {
		return x.InvalidTotal
	}
	return 0
}

func (x *Gateway) GetGoroutineTotal() int64 {
	if x != nil {
		return x.GoroutineTotal
	}
	return 0
}

func (x *Gateway) GetMemUsed() float32 {
	if x != nil {
		return x.MemUsed
	}
	return 0
}

func (x *Gateway) GetCpuUsed() float32 {
	if x != nil {
		return x.CpuUsed
	}
	return 0
}

var File_internal_model_gateway_proto protoreflect.FileDescriptor

var file_internal_model_gateway_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x86, 0x02, 0x0a, 0x07, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x70, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x6f,
	0x74, 0x61, 0x6c, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x5f,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x64, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0c, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12,
	0x27, 0x0a, 0x0f, 0x67, 0x6f, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x5f, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x67, 0x6f, 0x72, 0x6f, 0x75, 0x74,
	0x69, 0x6e, 0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x65, 0x6d, 0x5f,
	0x75, 0x73, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x55,
	0x73, 0x65, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x70, 0x75, 0x5f, 0x75, 0x73, 0x65, 0x64, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x63, 0x70, 0x75, 0x55, 0x73, 0x65, 0x64, 0x42, 0x0a,
	0x5a, 0x08, 0x2e, 0x2e, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_internal_model_gateway_proto_rawDescOnce sync.Once
	file_internal_model_gateway_proto_rawDescData = file_internal_model_gateway_proto_rawDesc
)

func file_internal_model_gateway_proto_rawDescGZIP() []byte {
	file_internal_model_gateway_proto_rawDescOnce.Do(func() {
		file_internal_model_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_model_gateway_proto_rawDescData)
	})
	return file_internal_model_gateway_proto_rawDescData
}

var file_internal_model_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_model_gateway_proto_goTypes = []interface{}{
	(*Gateway)(nil), // 0: model.gateway
}
var file_internal_model_gateway_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_model_gateway_proto_init() }
func file_internal_model_gateway_proto_init() {
	if File_internal_model_gateway_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_model_gateway_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gateway); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_model_gateway_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_model_gateway_proto_goTypes,
		DependencyIndexes: file_internal_model_gateway_proto_depIdxs,
		MessageInfos:      file_internal_model_gateway_proto_msgTypes,
	}.Build()
	File_internal_model_gateway_proto = out.File
	file_internal_model_gateway_proto_rawDesc = nil
	file_internal_model_gateway_proto_goTypes = nil
	file_internal_model_gateway_proto_depIdxs = nil
}
