services:
  nats-1:
    image: docker.io/nats
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats-1-data:/data
    command:
      - "--name=nats-1"
      - "--cluster_name=eim"
      - "--cluster=nats://nats-1:6222"
      - "--routes=nats-route://nats-1:6222,nats-route://nats-2:6222,nats-route://nats-3:6222"
      - "--http_port=8222"
      - "--js"
      - "--sd=/data"

  nats-2:
    image: docker.io/nats
    restart: always
    ports:
      - "4223:4222"
      - "8223:8222"
    volumes:
      - nats-2-data:/data
    command:
      - "--name=nats-2"
      - "--cluster_name=eim"
      - "--cluster=nats://nats-2:6222"
      - "--routes=nats-route://nats-1:6222,nats-route://nats-2:6222,nats-route://nats-3:6222"
      - "--http_port=8222"
      - "--js"
      - "--sd=/data"

  nats-3:
    image: docker.io/nats
    restart: always
    ports:
      - "4224:4222"
      - "8224:8222"
    volumes:
      - nats-3-data:/data
    command:
      - "--name=nats-3"
      - "--cluster_name=eim"
      - "--cluster=nats://nats-3:6222"
      - "--routes=nats-route://nats-1:6222,nats-route://nats-2:6222,nats-route://nats-3:6222"
      - "--http_port=8222"
      - "--js"
      - "--sd=/data"

volumes:
  nats-1-data:
    driver: local
  nats-2-data:
    driver: local
  nats-3-data:
    driver: local