version: '3'
services:
  etcd-1:
    image: "quay.io/coreos/etcd:v3.4.7"
    entrypoint: /usr/local/bin/etcd
    restart: always
    command:
      - '--name=etcd-1'
      - '--data-dir=/etcd_data'
      - '--initial-advertise-peer-urls=http://172.21.0.11:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://172.21.0.11:2379'
      - '--initial-cluster-token=mys1cr2tt1k7n'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd-1=http://172.21.0.11:2380,etcd-2=http://172.21.0.12:2380,etcd-3=http://172.21.0.13:2380'
      - '--initial-cluster-state=new'
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      etcd:
        ipv4_address: 172.21.0.11
    volumes:
      - ${EIM_DATA_DIR}/etcd/etcd-1:/etcd_data

  etcd-2:
    image: "quay.io/coreos/etcd:v3.4.7"
    entrypoint: /usr/local/bin/etcd
    restart: always
    command:
      - '--name=etcd-2'
      - '--data-dir=/etcd_data'
      - '--initial-advertise-peer-urls=http://172.21.0.12:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://172.21.0.12:2379'
      - '--initial-cluster-token=mys1cr2tt1k7n'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd-1=http://172.21.0.11:2380,etcd-2=http://172.21.0.12:2380,etcd-3=http://172.21.0.13:2380'
      - '--initial-cluster-state=new'
    ports:
      - "2479:2379"
      - "2480:2380"
    networks:
      etcd:
        ipv4_address: 172.21.0.12
    volumes:
      - ${EIM_DATA_DIR}/etcd/etcd-2:/etcd_data
  etcd-3:
    image: "quay.io/coreos/etcd:v3.4.7"
    entrypoint: /usr/local/bin/etcd
    restart: always
    command:
      - '--name=etcd-3'
      - '--data-dir=/etcd_data'
      - '--initial-advertise-peer-urls=http://172.21.0.13:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://172.21.0.13:2379'
      - '--initial-cluster-token=mys1cr2tt1k7n'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd-1=http://172.21.0.11:2380,etcd-2=http://172.21.0.12:2380,etcd-3=http://172.21.0.13:2380'
      - '--initial-cluster-state=new'
    ports:
      - "2579:2379"
      - "2580:2380"
    networks:
      etcd:
        ipv4_address: 172.21.0.13
    volumes:
      - ${EIM_DATA_DIR}/etcd/etcd-3:/etcd_data

networks:
  etcd:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
